// key_map.cpp — GENERATED (do not hand-edit).
// Exact content of KEY_MAP in src/client.rs (rustdesk@d1013487), translated entry-for-entry:
//   Key::Chr(c) -> Key::chr(c)  |  Key::ControlKey(k) -> Key::control_key(hbb::k).
// Notes: VK_F12 appears twice upstream with the same value (HashMap keeps one;
// std::unordered_map insert keeps the first — same observable map).
// Generator: python3 extraction, see examples/11_*/README.md.
#include <rustdesk/client.hpp>

namespace rustdesk {

const std::unordered_map<std::string, Key>& key_map() {
    static const auto* m = new std::unordered_map<std::string, Key>({
        {"VK_A", Key::chr('a')},
        {"VK_B", Key::chr('b')},
        {"VK_C", Key::chr('c')},
        {"VK_D", Key::chr('d')},
        {"VK_E", Key::chr('e')},
        {"VK_F", Key::chr('f')},
        {"VK_G", Key::chr('g')},
        {"VK_H", Key::chr('h')},
        {"VK_I", Key::chr('i')},
        {"VK_J", Key::chr('j')},
        {"VK_K", Key::chr('k')},
        {"VK_L", Key::chr('l')},
        {"VK_M", Key::chr('m')},
        {"VK_N", Key::chr('n')},
        {"VK_O", Key::chr('o')},
        {"VK_P", Key::chr('p')},
        {"VK_Q", Key::chr('q')},
        {"VK_R", Key::chr('r')},
        {"VK_S", Key::chr('s')},
        {"VK_T", Key::chr('t')},
        {"VK_U", Key::chr('u')},
        {"VK_V", Key::chr('v')},
        {"VK_W", Key::chr('w')},
        {"VK_X", Key::chr('x')},
        {"VK_Y", Key::chr('y')},
        {"VK_Z", Key::chr('z')},
        {"VK_0", Key::chr('0')},
        {"VK_1", Key::chr('1')},
        {"VK_2", Key::chr('2')},
        {"VK_3", Key::chr('3')},
        {"VK_4", Key::chr('4')},
        {"VK_5", Key::chr('5')},
        {"VK_6", Key::chr('6')},
        {"VK_7", Key::chr('7')},
        {"VK_8", Key::chr('8')},
        {"VK_9", Key::chr('9')},
        {"VK_COMMA", Key::chr(',')},
        {"VK_SLASH", Key::chr('/')},
        {"VK_SEMICOLON", Key::chr(';')},
        {"VK_QUOTE", Key::chr('\'')},
        {"VK_LBRACKET", Key::chr('[')},
        {"VK_RBRACKET", Key::chr(']')},
        {"VK_BACKSLASH", Key::chr('\\')},
        {"VK_MINUS", Key::chr('-')},
        {"VK_PLUS", Key::chr('=')},
        {"VK_DIVIDE", Key::control_key(hbb::Divide)},
        {"VK_MULTIPLY", Key::control_key(hbb::Multiply)},
        {"VK_SUBTRACT", Key::control_key(hbb::Subtract)},
        {"VK_ADD", Key::control_key(hbb::Add)},
        {"VK_DECIMAL", Key::control_key(hbb::Decimal)},
        {"VK_F1", Key::control_key(hbb::F1)},
        {"VK_F2", Key::control_key(hbb::F2)},
        {"VK_F3", Key::control_key(hbb::F3)},
        {"VK_F4", Key::control_key(hbb::F4)},
        {"VK_F5", Key::control_key(hbb::F5)},
        {"VK_F6", Key::control_key(hbb::F6)},
        {"VK_F7", Key::control_key(hbb::F7)},
        {"VK_F8", Key::control_key(hbb::F8)},
        {"VK_F9", Key::control_key(hbb::F9)},
        {"VK_F10", Key::control_key(hbb::F10)},
        {"VK_F11", Key::control_key(hbb::F11)},
        {"VK_F12", Key::control_key(hbb::F12)},
        // duplicate upstream entry (VK_F12 repeats with the same value)
        {"VK_F12", Key::control_key(hbb::F12)},
        {"VK_ENTER", Key::control_key(hbb::Return)},
        {"VK_CANCEL", Key::control_key(hbb::Cancel)},
        {"VK_BACK", Key::control_key(hbb::Backspace)},
        {"VK_TAB", Key::control_key(hbb::Tab)},
        {"VK_CLEAR", Key::control_key(hbb::Clear)},
        {"VK_RETURN", Key::control_key(hbb::Return)},
        {"VK_SHIFT", Key::control_key(hbb::Shift)},
        {"VK_CONTROL", Key::control_key(hbb::Control)},
        {"VK_MENU", Key::control_key(hbb::Menu)},
        {"VK_PAUSE", Key::control_key(hbb::Pause)},
        {"VK_CAPITAL", Key::control_key(hbb::CapsLock)},
        {"VK_KANA", Key::control_key(hbb::Kana)},
        {"VK_HANGUL", Key::control_key(hbb::Hangul)},
        {"VK_JUNJA", Key::control_key(hbb::Junja)},
        {"VK_FINAL", Key::control_key(hbb::Final)},
        {"VK_HANJA", Key::control_key(hbb::Hanja)},
        {"VK_KANJI", Key::control_key(hbb::Kanji)},
        {"VK_ESCAPE", Key::control_key(hbb::Escape)},
        {"VK_CONVERT", Key::control_key(hbb::Convert)},
        {"VK_SPACE", Key::control_key(hbb::Space)},
        {"VK_PRIOR", Key::control_key(hbb::PageUp)},
        {"VK_NEXT", Key::control_key(hbb::PageDown)},
        {"VK_END", Key::control_key(hbb::End)},
        {"VK_HOME", Key::control_key(hbb::Home)},
        {"VK_LEFT", Key::control_key(hbb::LeftArrow)},
        {"VK_UP", Key::control_key(hbb::UpArrow)},
        {"VK_RIGHT", Key::control_key(hbb::RightArrow)},
        {"VK_DOWN", Key::control_key(hbb::DownArrow)},
        {"VK_SELECT", Key::control_key(hbb::Select)},
        {"VK_PRINT", Key::control_key(hbb::Print)},
        {"VK_EXECUTE", Key::control_key(hbb::Execute)},
        {"VK_SNAPSHOT", Key::control_key(hbb::Snapshot)},
        {"VK_INSERT", Key::control_key(hbb::Insert)},
        {"VK_DELETE", Key::control_key(hbb::Delete)},
        {"VK_HELP", Key::control_key(hbb::Help)},
        {"VK_SLEEP", Key::control_key(hbb::Sleep)},
        {"VK_SEPARATOR", Key::control_key(hbb::Separator)},
        {"VK_NUMPAD0", Key::control_key(hbb::Numpad0)},
        {"VK_NUMPAD1", Key::control_key(hbb::Numpad1)},
        {"VK_NUMPAD2", Key::control_key(hbb::Numpad2)},
        {"VK_NUMPAD3", Key::control_key(hbb::Numpad3)},
        {"VK_NUMPAD4", Key::control_key(hbb::Numpad4)},
        {"VK_NUMPAD5", Key::control_key(hbb::Numpad5)},
        {"VK_NUMPAD6", Key::control_key(hbb::Numpad6)},
        {"VK_NUMPAD7", Key::control_key(hbb::Numpad7)},
        {"VK_NUMPAD8", Key::control_key(hbb::Numpad8)},
        {"VK_NUMPAD9", Key::control_key(hbb::Numpad9)},
        {"CTRL_ALT_DEL", Key::control_key(hbb::CtrlAltDel)},
        {"LOCK_SCREEN", Key::control_key(hbb::LockScreen)},
    });
    return *m;
}

}  // namespace rustdesk
